### PR TITLE
Update mine rebuilder userscript

### PR DESCRIPTION
**Pull request by SasSam**
This is an update for @PiTi2k5 's `user_mine_rebuild.js` userscript.

We can now switch between 2 options:
- show all checkboxes for all mines, regardless
- show checkboxes for mines only where they can be built. In this case, it doesn't show a checkbox if a mine is already built or a depo has not been found yet.

image

image

### CODE REVIEW

**Comment by fedorovvl** [comment]
@PiTi2k5 you approve this?

**Comment by PiTi2k5** [comment]
Without combobox on each deposit, the templates are useless or not?

**Comment by SasSam** [comment]
@PiTi2k5 and I had a quick chat, and we agreed to add a radio button in the header that will show all checkboxes or only the available ones. Let's put this PR on hold till then.

**Comment by SasSam** [comment]
The update has been pushed.

**Comment by fedorovvl** [comment]
i see u using "game" variable for storing DepositDepletedGameScriptKeys.SWITCH_STATUS.. why? its not saving to settings ang "game" is class variable..

**Comment by SasSam** [comment]
> i see u using "game" variable for storing DepositDepletedGameScriptKeys.SWITCH_STATUS.. why? its not saving to settings ang "game" is class variable.. instead of this u can use settings file.. for ex
> 

It just stores the radio button's state while the client is running. So, if you close the modal and reopen it, the radio button's state will be restored. But I don't think we need to save this setting permanently in a file.

I know the game is the main object, but the set key-value won't conflict with anything because it has a unique prefix.

**Comment by fedorovvl** [comment]
> I know the game is the main object, but the set key-value won't conflict with anything because it has a unique prefix.

not necessary to escape from script scope.. u can use any variable defined inside script

**Comment by SasSam** [comment]
> not necessary to escape from script scope.. u can use any variable defined inside script

Ok, I've pushed the update for this. Using a global variable within the script instead of the `game` object.

**Pull request merged**
